### ISSUE TITLE
Vacant lot color encoding by type

### ISSUE THREAD

**Issue by sphalt** [jaspreetKsohal/CS594-EDH#21]
different colors for the different types of vacant lots

**Comment by jaspreetKsohal** [comment]
The original vacant lots files do not have complete data.
<img width="900" alt="screen shot 2018-11-29 at 10 30 28 pm" src="https://user-images.githubusercontent.com/31716381/49268735-c96b7f00-f426-11e8-8f08-963d966cc2ad.png">

And the files downloaded from Chicago data portal do not have vacant lot type field.
